CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(10) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    settlement_start_day SMALLINT DEFAULT 1 NOT NULL,
    withdrawn_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_login_id UNIQUE (login_id),
    CONSTRAINT chk_users_settlement_start_day CHECK (settlement_start_day BETWEEN 1 AND 28)
);

CREATE TABLE financial_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    cost_type VARCHAR(20) NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_financial_categories_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_financial_categories_user_name UNIQUE (user_id, category_name),
    CONSTRAINT chk_financial_categories_type_cost CHECK (
        (transaction_type = 'INCOME' AND cost_type = 'NONE') OR
        (transaction_type = 'EXPENSE' AND cost_type IN ('FIXED', 'VARIABLE'))
    )
);
CREATE INDEX idx_financial_categories_user_active ON financial_categories (user_id, is_active);

CREATE TABLE financial_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    memo VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_financial_records_category FOREIGN KEY (category_id)
        REFERENCES financial_categories (category_id),
    CONSTRAINT chk_financial_records_amount_positive CHECK (amount > 0)
);
CREATE INDEX idx_financial_records_category_date ON financial_records (category_id, record_date);
CREATE INDEX idx_financial_records_record_date ON financial_records (record_date DESC);

CREATE TABLE daily_notes (
    note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    note_date DATE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_daily_notes_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_daily_notes_user_date UNIQUE (user_id, note_date)
);
CREATE INDEX idx_daily_notes_user_date ON daily_notes (user_id, note_date);
