CREATE TABLE financial_record_imports (
    import_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    record_count INTEGER NOT NULL,
    note_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_financial_record_imports_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_financial_record_imports_user_hash UNIQUE (user_id, file_hash)
);

CREATE INDEX idx_financial_record_imports_user_created
    ON financial_record_imports (user_id, created_at DESC);

CREATE TABLE financial_import_column_mappings (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    normalized_header VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_financial_import_mappings_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_financial_import_mappings_category FOREIGN KEY (category_id) REFERENCES financial_categories (category_id),
    CONSTRAINT uk_financial_import_mappings_user_header UNIQUE (user_id, normalized_header)
);

CREATE INDEX idx_financial_import_mappings_user
    ON financial_import_column_mappings (user_id);
